### ISSUE TITLE
DATA model - auto pointage de temps

### ISSUE THREAD

**Issue by evarisk-theo** [Eoxia/doliproject#23]
pointage du temps :

projet développement, une tâche par jour/semaine/mois
en fin de journée, tout le temps non pointé est pointé sur cette tache

tâche par défaut

projet développement avec une tache par module
projet rh avec tache vacances, maladie, tache heure supplémentaire, jour férié etc.
projet développement spécifique avec une tache par sprint
on définit la tâche sur laquelle on est en ce moment
en fin de journée le temps consommé est rapatrié dans la tâche
petit popup : tant de temps pas pointé, qu'avez vous fait aujourd'hui ? input texte qui sera ajoutée dans le temps consommé

**Comment by lmag** [comment]
Pointage du temps :

- [ ] Choix du projet défaut de pointage du temps : 
- [ ] -Choix de la tache de complétion du temps pour la période
- [ ] Contrôler le temps par journée
- [ ] En fin de journée, tout le temps non pointé est pointé sur la tache par défaut

Pour chaque salariés
Création du projet "RH-Nom-Prénom"
Création des taches standards
- [ ] Absence
- [ ] Arrêt de travail
- [ ] Congés payés
- [ ] Congés maladies
- [ ] Autres congés
- [ ] RTT

Lors de la création des demandes de congés

- [ ] Pointage du temps sur les taches en relation avec la demande
